
# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY ./usuarios_ms/ .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development
ENV SECRET_KEY=SECRET_KEY
ENV DATABASE_URL='postgres://usuarios_ms:rasi@db:5432/usuarios_db'
ENV AUTH0_CLIENT_ID = 'ADExS2cKbGn4iKH4emUJnLW7aptcZHPx'
ENV AUTH0_CLIENT_SECRET = '-HIfKrl5KNE8EGFGgCrLkpPfQUSlvjQjXcqvY6Ki625vM7-F7D0CyhZsODnha46D'
ENV AUTH0_DOMAIN = 'rasimedical-auth.us.auth0.com'
ENV AUTH0_CALLBACK_URL = 'http://34.160.204.45/usuarios/callback/'
ENV AUTH0_AUDIENCE = ''

# Run app.py when the container launches
CMD ["flask", "run", "--port=8080"]
