version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuarios_ms
      POSTGRES_PASSWORD: rasi
      POSTGRES_DB: usuarios_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
