# Use the official MongoDB image
FROM mongo:latest

# Set environment variables for MongoDB
# These are optional and can be customized as needed
ENV MONGO_INITDB_ROOT_USERNAME=historias_ms
ENV MONGO_INITDB_ROOT_PASSWORD=rasi

# Expose the default MongoDB port
EXPOSE 27017

# Set the default command to run when starting the container
CMD ["mongod"]
